set nocompatible

" basic configurations
set ts=4 " tabstop=4
set sw=4 " shiftwidth=4
set sts=4 " softtabstop=4
set et " expandtab
set ls=2 " laststatus=2
set cul " cursorline
set ai " autoindent
set is " incsearch
filetype plugin indent on
set hls " hlsearch
set nu " number
set rnu " relativenumber
set showcmd
colo desert
syntax enable

" additional configurations
" colo molokayo
set mouse=n
set autochdir

" Set true color
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"

" encoding
set fileencodings=ucs-bom,utf-8,cp932,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
